import React, { createContext, useState } from 'react';
const themes = {
    dark: {
        splash: 'black',
        backgroundColor: '#0B0C0F',
        barColor: 'light-content',
        editProfileButton: '#222222',
        editOutline: '#FFFFFF',
        profileImg: 'url(#paint0_radial_575_887)',
        colorCity: '#C0A5F3',
        colorName: '#FFFFFF',
        colorUsername: 'rgba(192, 165, 243, 0.54)',
        colorHeader: '#BDBADE',
        colorText: '#E2E4E9',
        colorEditProfile: '#222222',
        colorMenu1: 'white',
        colorMenu2: 'white',
        colorMenu3: 'white',
        gradientL: '#AEA1FF',
        gradientR:'#805FBE',
        gradientTextL: '#BDBADE',
        gradientTextR:'#BDBADE',
        shadowInstagram: '#8B3C93',
        HeaderText:"#913E98",
        shadowFacebook: '#B378FF',
        gradientFacebook: 'url(#paint1_linear_717_1554)',
        outlineFacebook: '#0A0A0B',
        shadowSpotify: '#715AB0',
        gradientSpotify: 'url(#paint0_linear_781_1384)',
        shadowTiktok: '#886DD6',
        tabBarBackgroundColor: '#05040A',
        activeTintColor:  "#BDBADE",
        inactiveTintColor: "#767676",
        profileActive: '#BDBADE',
        discoverActive: '#BDBADE',
        mischiefActive: '#BDBADE',
        sidebarProfileGradient: 'url(#paint1_radial_608_852)',
        approveBack: '#A27ED0',
        rejectBack: '#530AB1',
        deleteBack: '#530AB1',
        cardBackground: "#222222",
        cardAvatarBorder: "url(#paint0_linear_835_1398)",
        cardAvatarBackground: "url(#paint1_linear_835_1398)",
        cardAvatarText: "#C1ADD3",
        filterBack: "url(#paint0_linear_683_1390)",
        filterBorder: "url(#paint1_linear_683_1390)",
        search1: "url(#paint0_linear_834_1414)",
        search2: "url(#paint1_linear_834_1414)",
        search3: "url(#paint2_linear_834_1414)",
        searchText:  "#000000",
        platform: 'ios',
        searchInputContainer: "#000000",
        searchInputText: "#000000",
        bottomModalBack: "black",
        resetTextColor: "white",
        resetButtonColor: "#B0AAF6",
        filterTextColor: "white",
        filterButtonColor: "#31204B",
        checkedColor: "#8557E4",
        friendText:"#8D69AD",
        NotificationButton: "white",
        messageAvatarText: "black",
        userMessageBackground: '#E5CBFF',
        friendMessageBackground: '#CECBF1',
        chatBackground: '#161617',
        inputBarBackground: '#0E0C11',
        inputTextBackground: '#161617',
        decisionColor: 'white',
        requestColorName: '#FFFFFF',
        friendColorName: '#FFFFFF',
        updateButtonL: '#814AE8',
        updateButtonR: '#9C98CD',
        messageTextColors: "#241453",
        settingsGeneral: '#9F99DB',
        settingsText: 'white',
        settingsSwitchOn: '#C097E0',
        settingSwitchOff: '#EAEAEA',
        settingsButton: '#F9D1FA',
        settingsDivider: '#BDBADE',
        settingsHeader: '#161617',
        settingsLocateMeButon: '#6775F3',
        settingsLocateMeText: 'white',
        sliderMin: '#6775F3',
        sliderMax: '#BDBADE',
        errorText: '#816CFF',

        circleFill: '#0B0C0F',

        circle1Outline: '#272850',
        circle2Outline: '#1D1E3C',
        circle3Outline: '#141529',
        circle4Outline: '#141529',
        circle5Outline: '#0B0C17',
        locationIconOuterFill:'#8D68AD',
        locationIconInnerFill: '#0B0C0F',
        instagramG1: '#8B53D3',
        instagramG2: '#9722AA',
        facebookG1: '#523E89',
        facebookG2: '#B378FF',
        spotifyG1: '#7862B6',
        spotifyG2: '#875788',
        tiktokG1: '#865EBA',
        tiktokG2: '#7A5AD2',
         inactiveTabProg: '#262626',

    },
    light: {
        inputBarBackground: '#F0EBFF',
        updateButtonL: '#2D1E48',
        updateButtonR: '#71347E',
        splash: '#FFFFFF',
        backgroundColor: '#FFFFFF',
        barColor: 'dark-content',
        editProfileButton: '#FFFFFF',
        editOutline: '#300E41',
        profileImg: 'url(#paint0_radial_478_2717)',
        colorCity: '#48428A',
        colorName: '#300E41',
        colorUsername: 'rgba(34, 0, 55, 0.54)',
        colorHeader: '#8D69AD',
        colorText: '#0A0317',
        colorEditProfile: 'white',
        colorMenu1: '#300E41',
        colorMenu2: '#300E41',
        colorMenu3: '#300E41',
        gradientL: '#43176C',
        gradientR:'#43176C',
        gradientTextL: '#6E0B9C',
        gradientTextR:'#6E0B9C',
        shadowInstagram: '#F9514A',
        shadowFacebook: '#0675E8',
        gradientFacebook: 'url(#paint1_linear_717_1555)',
        outlineFacebook: 'white',
        shadowSpotify: '#2BBB5E',
        gradientSpotify: '#1ED760',
        friendText:"#5A53AC",
        shadowTiktok: '#EC7B98',
        tabBarBackgroundColor: '#F6F6F7',
        activeTintColor:  "#8D69AD",
        inactiveTintColor: "#B6B9C9",
        profileActive: '#8D69AD',
        discoverActive: '#8D69AD',
        mischiefActive: '#8D69AD',
        sidebarProfileGradient: 'url(#paint0_radial_608_852)',
        cardBackground:"#F6F6F6",
        cardAvatarBorder: "url(#paint0_linear_834_1398)",
        cardAvatarBackground: "url(#paint1_linear_834_1398)",
        cardAvatarText: "#2D1E48",
        messageAvatarText: "white",
        approveBack: '#530AB1',
        rejectBack: '#24292E',
        deleteBack: '#24292E',
        decisionColor: '#24292E',
        filterBack: "url(#paint0_linear_683_1391)",
        filterBorder: "url(#paint1_linear_683_1391)",
        search1: "url(#paint0_linear_834_1415)",
        search2: "url(#paint1_linear_834_1415)",
        search3: "url(#paint2_linear_834_1415)",
        searchText: "#270C5A",
        platform: 'ios',
        searchInputContainer: "#270C5A",
        searchInputText: "#270C5A",
        bottomModalBack: "#E2E4E9",
        resetTextColor: "white",
        resetButtonColor: "#B694F5",
        filterTextColor: "white",
        filterButtonColor: "#4E17B5",
        checkedColor: "#532A66",
        HeaderText:"#2D1E48",
        NotificationButton: "#8D69AD",
        userMessageBackground: '#AC6BAD',
        friendMessageBackground: '#2D1E48',
        chatBackground: '#EFEFEF',
        inputTextBackground: '#FFFFFF',
        requestColorName: '#24292E',
        friendColorName: '#24292E',
        messageTextColors: "white",
        settingsGeneral: '#2C0D66',
        settingsText: 'black',
        settingsSwitchOn: '#B078DC',
        settingSwitchOff: '#EAEAEA',
        settingsButton: '#B997CD',
        settingsDivider: '#EAEAEA',
        settingsHeader: '#FBFBFB',
        settingsLocateMeButon: '#502B6C',
        settingsLocateMeText: 'white',
        sliderMin: '#502B6C',
        sliderMax: '#EEE6F3',
        errorText: '#6800B9',

        circle1Outline: '#FBEEFF',
        circleFill: '#FFFFFF',
        circle2Outline: '#EAD5F1',
        circle3Outline: '#E1C4EC',
        circle4Outline: '#F3D9FC',
        circle5Outline: '#F3D9FC',
        locationIconOuterFill:'#5B1175',
        locationIconInnerFill: '#FFFFFF',

        instagramG1: '#C837AB',
        instagramG2: '#8C2E79',
        facebookG1: '#0062E0',
        facebookG2: '#14A1C0',
        spotifyG1: '#2BBB5E',
        spotifyG2: '#2BBB5E',
        tiktokG1: '#7B0D63',
        tiktokG2: '#AB28E9',
         inactiveTabProg: '#DFDFDF',
    },
    sport: {
        removeFriendX: '#992A96',
        updateButtonL: '#07E9F8',
        updateButtonR: '#3543BB',
        splash: '#131429',
        backgroundColor: '#131429',
        barColor: 'light-content',
        editProfileButton: '#1A1C35',
        editOutline: '#A93ED0',
        profileImg: 'url(#paint0_radial_676_1945)',
        colorCity: '#C22E83',
        colorName: '#FFFFFF',
        colorUsername: '#5C6CF1',
        colorHeader: '#9B2A6B',
        colorText: '#E2E4E9',
        colorEditProfile:'url(#paint0_linear_676_2012)',
        colorMenu1: 'url(#paint0_linear_676_2011)',
        colorMenu2: 'url(#paint1_linear_676_2011)',
        colorMenu3: 'url(#paint2_linear_676_2011)',
        gradientL: '#C22E83',
        gradientR:'#8027A1',
        gradientTextL: '#C22E83',
        gradientTextR:'#A93ED0',
        shadowInstagram: '#B52BEB',
        shadowFacebook: '#2DB5E7',
        gradientFacebook: 'url(#paint0_linear_781_1380)',
        outlineFacebook: '#131429',
        shadowSpotify: '#D984EB',
        gradientSpotify: 'url(#paint0_linear_781_1385)',
        shadowTiktok: '#8580DF',
        tabBarBackgroundColor: '#090915',
        activeTintColor:  "#A02A92",
        inactiveTintColor: "#666790",
        profileActive: '#C12E84',
        discoverActive: '#982A96',
        mischiefActive: '#89289D',
        sidebarProfileGradient: 'url(#paint0_radial_676_2229)',
        cardBackground:"#282841",
        cardAvatarBorder: "url(#paint0_linear_836_1398)",
        cardAvatarBackground: "url(#paint1_linear_836_1398)",
        cardAvatarText: "#2383D5",
        filterBack: "url(#paint0_linear_683_1392)",
        filterBorder: "url(#paint1_linear_683_1392)",
        approveBack: '#FFA192',
        rejectBack: '#FD1892',
        deleteBack: '#FD1892',
        decisionColor: 'white',
        search1: "url(#paint0_linear_834_1416)",
        search2: "url(#paint1_linear_834_1416)",
        search3: "url(#paint2_linear_834_1416)",
        searchText:  "#848487",
        platform: 'ios',
        searchInputContainer: "#9696AF",
        searchInputText: "#282841",
        bottomModalBack: "#0F0F1A",
        resetTextColor: "white",
        resetButtonColor: "#C22E83",
        filterTextColor: "white",
        filterButtonColor: "#751897",
        checkedColor: "#C22E83",
        friendText:"#992A96",
        HeaderText:"#C22E83",
        NotificationButton: "white",
        messageAvatarText: "#059885",
        userMessageBackground: '#C22E83',
        friendMessageBackground: '#8027A1',
        chatBackground: '#15162D',
        inputBarBackground: '#131328',
        inputTextBackground: '#20203D',
        requestColorName: '#FE5D92',
        friendColorName: '#E09AF2',
        messageTextColors: "white",
        settingsGeneral: '#F3A9D4',
        settingsText: 'white',
        settingsSwitchOn: '#A42B91',
        settingSwitchOff: 'grey',
        settingsButton: '#C22E83',
        settingsDivider: '#AC2B82',
        settingsHeader: '#0E0F20',
        settingsLocateMeButon: '#BE6CBB',
        settingsLocateMeText: '#0E0F20',
        sliderMin: '#AC2B82',
        sliderMax: '#FFE5F4',
        errorText: '#E09AF2',

        circle1Outline: '#3F2C58',
        circleFill: '#131429',
        circle2Outline: '#312145',
        circle3Outline: '#2B1D3D',
        circle4Outline: '#2B1D3D',
        circle5Outline: '#8027A1',
        locationIconOuterFill:'#C22E83',
        locationIconInnerFill: '#131429',


        instagramG1: '#835EEE',
        instagramG2: '#BB24E2',
        facebookG1: '#2CB7E8',
        facebookG2: '#08F1E0',
        spotifyG1: '#D67EEE',
        spotifyG2: '#E9B4F5',
        tiktokG1: '#A3CFEF',
        tiktokG2: '#386F8E',
         inactiveTabProg: '#25254F',
    },
    deep: {
        removeFriendX: '#92EBFF',
        updateButtonL: '#0A2E43',
        updateButtonR: '#11363F',
        splash: '#0A0A0B',
        backgroundColor: '#0A0A0B',
        barColor: 'light-content',
        editProfileButton: '#162A2F',
        editOutline: '#E8FEFF',
        profileImg: 'url(#paint0_radial_676_1946)',
        colorCity: '#579EA5',
        colorName: '#FFFFFF',
        colorUsername: '#8DBDF6',
        colorHeader: '#579EA5',
        colorText: '#E2E4E9',
        colorEditProfile:'url(#paint0_linear_676_2012)',
        colorMenu1: 'white',
        colorMenu2: 'white',
        colorMenu3: 'white',
        gradientL: '#1D5189',
        gradientR:'#418FBD',
        gradientTextL: '#0A7FB1',
        gradientTextR:'#44B2B2',
        shadowInstagram: '#2B83EB',
        shadowFacebook: '#2DB5E7',
        gradientFacebook: 'url(#paint0_linear_781_1380)',
        outlineFacebook: '#131429',
        shadowSpotify: '#84EBC6',
        gradientSpotify: 'url(#paint0_linear_781_1386)',
        shadowTiktok: '#A3CFEF',
        tabBarBackgroundColor: '#090915',
        activeTintColor:  "#73AED0",
        inactiveTintColor: "#484848",
        profileActive: '#2C617F',
        discoverActive: '#2C617F',
        mischiefActive: '#2C617F',
        sidebarProfileGradient: 'url(#paint0_radial_676_2230)',
        cardBackground:"#232527",
        cardAvatarBorder: "url(#paint0_linear_836_1399)",
        cardAvatarBackground: "url(#paint1_linear_836_1399)",
        cardAvatarText: "#488C9C",
        filterBack: "url(#paint0_linear_683_1393)",
        filterBorder: "url(#paint1_linear_683_1393)",
        approveBack: '#7ED0D0',
        rejectBack: '#0A7FB1',
        deleteBack: '#0A7FB1',
        decisionColor: 'white',
        search1: "url(#paint0_linear_834_1417)",
        search2: "url(#paint1_linear_834_1417)",
        search3: "url(#paint2_linear_834_1417)",
        searchText:  "#848487",
        platform: 'ios',
        searchInputContainer: "#9696AF",
        searchInputText: "#282841",
        bottomModalBack: "#0E131A",
        resetTextColor: "black",
        resetButtonColor: "#91AECB",
        filterTextColor: "white",
        filterButtonColor: "#357497",
        checkedColor: "#66DEFA",
        friendText:"#66DEFA",
        HeaderText:"#C22E83",
        NotificationButton: "white",
        messageAvatarText: "#178FB5",
        userMessageBackground: '#357497',
        friendMessageBackground: '#91AECB',
        chatBackground: '#1E2123',
        inputBarBackground: '#131328',
        inputTextBackground: '#20203D',
        requestColorName: '#488C9C',
        friendColorName: '#66DEFA',
        messageTextColors: "#04060B",
        settingsGeneral: '#4E838A',
        settingsText: 'white',
        settingsSwitchOn: '#498895',
        settingSwitchOff: '#EAEAEA',
        settingsButton: '#D1F0FA',
        settingsDivider: '#BADEDC',
        settingsHeader: '#090F10',
        settingsLocateMeButon: '#4E838A',
        settingsLocateMeText: 'white',
        sliderMin: '#0C758C',
        sliderMax: '#D3ECF3',
        errorText: '#02D3C6',

        circle1Outline: '#161E2E',
        circleFill: '#0A0A0B',
        circle2Outline: '#1B1A22',
        circle3Outline: '#18171A',
        circle4Outline: '#141A28',
        circle5Outline: '#19242E',
        locationIconOuterFill:'#273848',
        locationIconInnerFill: '#0E1319',

        instagramG1: '#235EB6',
        instagramG2: '#247CAE',
        facebookG1: '#2CB7E8',
        facebookG2: '#08F1E0',
        spotifyG1: '#7EEECC',
        spotifyG2: '#B4EDF5',
        tiktokG1: '#A3CFEF',
        tiktokG2: '#386F8E',
        inactiveTabProg: '#262626',

    }
}

const initialState = {
    dark: false,
    sport: false,
    deep: false,
    theme: themes.light,
    toggle: () => {},
    sportToggle: () => {},
    deepToggle: () => {}
}
const ThemeContext = createContext(initialState);

function ThemeProvider({ children }) {
    const [dark, setDark] = useState(true) // Default theme is light
    const [sport, setSport] = useState(true)
    const [deep, setDeep] = useState(false)
    // To toggle between dark and light modes
    const toggle = () => {
        setDark(!dark)
        setDeep(false)
        setSport(false)
        console.log('lightMode mode active ' + dark);
    }
    const sportToggle = () => {
        setDeep(false)
        setDark(true)
        setSport(!sport)
        console.log('sport Mode On');
    }

    const deepToggle = () => {
        setDark(true)
        setSport(false)
        setDeep(!deep)
        console.log('Deep Ocean Mode On');
    }
    // Filter the styles based on the theme selected
    const theme = deep ? themes.deep : (sport ? themes.sport : (dark ? themes.dark : themes.light))

    return (
        <ThemeContext.Provider value={{ dark, sport, deep, theme, toggle, sportToggle, deepToggle}}>
            {children}
        </ThemeContext.Provider>
    )
}

export { ThemeProvider, ThemeContext }